name: Avisar al Fork del cambio

on:
  push:
    branches:
      - main # O tu rama principal

jobs:
  ping-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar señal de actualización
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.FORK_TOKEN }}" \
          https://api.github.com/repos/nelsongn/Frontend-toyoxpress-v2/dispatches \
          -d '{"event_type": "original_updated"}'
